version: "0.2"
ignorePaths:
  - /apps/web/src/lib/data/news.json
  - /apps/web/src/lib/data/news_archive.json
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - package.json
ignoreRegExpList:
  - /[a-z0-9]{25}/gi
dictionaryDefinitions: []
dictionaries: []
enableCompoundWords: enable
words:
  - additionality
  - biofuels
  - callout
  - CCUS
  - cloudinary
  - Coerver
  - csstools
  - deslugify
  - Greenwashing
  - hygraph
  - iframe
  - Neue
  - Noto
  - oklab
  - OKLCH
  - parentheticals
  - rgba
  - RGGI
  - Roboto
  - seagrass
  - Segoe
  - skinnypug
  - stylesheet
  - superheading
  - tailwindcss
  - UNFCCC
  - Verra
  - VREC
  - VRECs
  - VREM
  - VRES
  - VREU
  - WBCSD
  - webp
  - wordmark
import: []
ignoreWords:
  - lorem
  - ipsum
